[[libpicosat]]
arch = "aarch64"
git-tree-sha1 = "8085ca78738a9a227332545bfd1b917509f9dba1"
os = "macos"

    [[libpicosat.download]]
    sha256 = "be5a8b83e491350c2b57d7c603fd61147de3b83e0c70a5b61d17a278fe15aeed"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.aarch64-apple-darwin.tar.gz"
[[libpicosat]]
arch = "aarch64"
git-tree-sha1 = "3df5809f0c0f82ba148c23ef3a18d1727595196c"
libc = "glibc"
os = "linux"

    [[libpicosat.download]]
    sha256 = "7cce25ce5c183d606dc256ace9375045c8cfe30918ad38fd8863fc1fd4cd6e52"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.aarch64-linux-gnu.tar.gz"
[[libpicosat]]
arch = "aarch64"
git-tree-sha1 = "d27be879a31ccf55edfc3b023e2f077f8158b844"
libc = "musl"
os = "linux"

    [[libpicosat.download]]
    sha256 = "d127af3a0e5ac7f5fc712cc0a14f1ff438c8f69197577731a10061aa0445e8c5"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.aarch64-linux-musl.tar.gz"
[[libpicosat]]
arch = "aarch64"
git-tree-sha1 = "65879ad1b001763a182f926c950b9e93a261f742"
os = "freebsd"

    [[libpicosat.download]]
    sha256 = "1608b280853c5d444d1dc21c899393a933900d6ee0239137bf9498ebe83f64fa"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.aarch64-unknown-freebsd.tar.gz"
[[libpicosat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "9136d86c8df7aad261f97aed8e30c79f9412367f"
libc = "glibc"
os = "linux"

    [[libpicosat.download]]
    sha256 = "1f61876de70c381135a4abb69951c0cccd178fdbb649ce2b540090499c3bdf5d"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.armv6l-linux-gnueabihf.tar.gz"
[[libpicosat]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e27ccde1c3d432cfa2f7d65c4baa6074c8d9eceb"
libc = "musl"
os = "linux"

    [[libpicosat.download]]
    sha256 = "0fe5e3814915c565f213c7e6d30a52b6a436e119aad7ed30125472474dbeccfa"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.armv6l-linux-musleabihf.tar.gz"
[[libpicosat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bc9a4205d6599ac5c4620fd8ac56792b39c8a9fb"
libc = "glibc"
os = "linux"

    [[libpicosat.download]]
    sha256 = "9da68e4c5da7d9b7a62ff5295b46cf153784fac440a2e3cfbf5ec40d89253ca4"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.armv7l-linux-gnueabihf.tar.gz"
[[libpicosat]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1e5aff3b59ddf801bab72c989cffd6e203df71ee"
libc = "musl"
os = "linux"

    [[libpicosat.download]]
    sha256 = "6b0f7d81fba30a68232930170a644600567417d5bc9b4ed5d23628147dc7aba7"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.armv7l-linux-musleabihf.tar.gz"
[[libpicosat]]
arch = "i686"
git-tree-sha1 = "fe61b7f08e4c187339917b24b2a7a5792d6cdf09"
libc = "glibc"
os = "linux"

    [[libpicosat.download]]
    sha256 = "3b2af59c887df3a3163adb992b1d2d6f8a11667b433f5d0f520adb5e937b94af"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.i686-linux-gnu.tar.gz"
[[libpicosat]]
arch = "i686"
git-tree-sha1 = "c5d96fa4885bfaa192821b47b628352590c0e893"
libc = "musl"
os = "linux"

    [[libpicosat.download]]
    sha256 = "a4efeaa193adf390c5390caef0a35a967268f66c2e7254cb77de599692a09192"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.i686-linux-musl.tar.gz"
[[libpicosat]]
arch = "i686"
git-tree-sha1 = "8ef3f3a0f71dff9eb3da0793a44ff969c52634aa"
os = "windows"

    [[libpicosat.download]]
    sha256 = "a1b66c8c55ff5ed9c718ffec4350adbe8fdc7c17f85eda1c00c0a119b2cd18b6"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.i686-w64-mingw32.tar.gz"
[[libpicosat]]
arch = "powerpc64le"
git-tree-sha1 = "bca2528647c745b084a38e214c6d9a70b39ccb7e"
libc = "glibc"
os = "linux"

    [[libpicosat.download]]
    sha256 = "355526571d9709b49051b66b897d682c5e2d4585f578b109ec504a670f045e7a"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.powerpc64le-linux-gnu.tar.gz"
[[libpicosat]]
arch = "riscv64"
git-tree-sha1 = "15cbea4b33824fa430522009ea87d678cc563820"
libc = "glibc"
os = "linux"

    [[libpicosat.download]]
    sha256 = "0231f6f70ac738e6822f4a56c5e92db31ad520188bf62ab02f70255e3197fe8a"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.riscv64-linux-gnu.tar.gz"
[[libpicosat]]
arch = "x86_64"
git-tree-sha1 = "35d2eae84d2ef2c132b1db6470dc25529c5fc78c"
os = "macos"

    [[libpicosat.download]]
    sha256 = "a4b0a8cc49f103b612b942c834d9e9b6f2c100d063c82f2f6d82d83230c16ca1"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.x86_64-apple-darwin.tar.gz"
[[libpicosat]]
arch = "x86_64"
git-tree-sha1 = "e58ce343ca2135e6eda9e09a6d7ebbaee7bae215"
libc = "glibc"
os = "linux"

    [[libpicosat.download]]
    sha256 = "63a9c6d21a8afc627b5891dc76b556e0ad774bb9db8b4db12cd892a3a3a28883"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.x86_64-linux-gnu.tar.gz"
[[libpicosat]]
arch = "x86_64"
git-tree-sha1 = "b0d01c79732c52b226343f7839710b603b694d54"
libc = "musl"
os = "linux"

    [[libpicosat.download]]
    sha256 = "6af4dcc21e3611adf7c12bc00ae214070cde02cb162e08d4d6e1d4d4a147aa32"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.x86_64-linux-musl.tar.gz"
[[libpicosat]]
arch = "x86_64"
git-tree-sha1 = "08482fb5affac2a8bc807a7f68d80fdba42cc73a"
os = "freebsd"

    [[libpicosat.download]]
    sha256 = "0881faf2837cd1bc3f5c943a1536abeddc99775b58b9060654381298f3d92253"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.x86_64-unknown-freebsd.tar.gz"
[[libpicosat]]
arch = "x86_64"
git-tree-sha1 = "a800e46ceacbc65f7da4535bd5af59854262a8b4"
os = "windows"

    [[libpicosat.download]]
    sha256 = "78d868ea094d0aa292eb719c0897cd3dc532a7cbc4deeee4e6000087a607ce93"
    url = "https://github.com/JuliaBinaryWrappers/libpicosat_jll.jl/releases/download/libpicosat-v965.0.2+0/libpicosat.v965.0.2.x86_64-w64-mingw32.tar.gz"
