# Autogenerated wrapper script for libpicosat_jll for armv6l-linux-gnueabihf
export libpicosat

JLLWrappers.@generate_wrapper_header("libpicosat")
JLLWrappers.@declare_library_product(libpicosat, "libpicosat.so")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpicosat,
        "lib/libpicosat.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
