# Autogenerated wrapper script for libpicosat_jll for i686-w64-mingw32
export libpicosat

JLLWrappers.@generate_wrapper_header("libpicosat")
JLLWrappers.@declare_library_product(libpicosat, "libpicosat.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpicosat,
        "bin\\libpicosat.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
