# Autogenerated wrapper script for libpicosat_jll for x86_64-apple-darwin
export libpicosat

JLLWrappers.@generate_wrapper_header("libpicosat")
JLLWrappers.@declare_library_product(libpicosat, "@rpath/libpicosat.dylib")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libpicosat,
        "lib/libpicosat.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
